### ISSUE TITLE
🚀 [feature]모임관련 API

### ISSUE THREAD

**Issue by minseo003** [jungmo-app/server#25]
# 🤖 기능 개요
모임에 관련된 crud를 구현한다

## ✅ Todo
- [x] 모임 생성 API
- [x] 모임 수정 API
- [x] 모임 조회 API
- [x] 내 모든 모임 조회 API
- [x] 모임 삭제 API
